# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:31800/api/scrapyard/version
X-Scrapyard-Auth: default:default

###

POST http://localhost:31800/api/add/bookmark
Content-Type: application/json
X-Scrapyard-Auth: default:default

{
    "name": "example node"
    ,"uri": "https://example.com"
    ,"path": "example/category"
    ,"tags": "test,example"
}

###

POST http://localhost:31800/api/list/nodes
Content-Type: application/json
X-Scrapyard-Auth: default:default

{
    "path": "misk"
#    ,"tags": "test,example"
#    ,"type": 2
}

###

GET http://localhost:31800/api/list/shelves
X-Scrapyard-Auth: default:default

###

GET http://localhost:31800/api/completion/groups
X-Scrapyard-Auth: default:default

###

GET http://localhost:31800/api/completion/tags
X-Scrapyard-Auth: default:default

###

POST http://localhost:31800/api/nodes/copy
Content-Type: application/json
X-Scrapyard-Auth: default:default

{
    "nodes": ["FCBE280D977CCCAB936558B89B584C04"],
    "dest": "20D939B0734E64F9A0818C26DCB61091"

}

###
